"""Create moodhistory table

Revision ID: 68c186d30cee
Revises: b699885a573a
Create Date: 2025-12-07 14:40:12.637664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68c186d30cee'
down_revision = 'b699885a573a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodhistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign Key to users table'),
    sa.Column('mood_score', sa.Integer(), nullable=False, comment='1-10 scale. Good for graphing on the Frontend.'),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True, comment="'Happy', 'Anxious', 'Neutral'. The LLM understands words better than numbers."),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="['work', 'deadline']. Stores why they feel this way. Essential for pattern recognition."),
    sa.Column('summary', sa.Text(), nullable=False, comment="'User is stressed about the demo tomorrow.'"),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Links this mood entry to a specific chat session (in case you need to debug).'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodhistory_created_at'), 'moodhistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_moodhistory_id'), 'moodhistory', ['id'], unique=False)
    op.create_index(op.f('ix_moodhistory_session_id'), 'moodhistory', ['session_id'], unique=False)
    op.create_index(op.f('ix_moodhistory_user_id'), 'moodhistory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moodhistory_user_id'), table_name='moodhistory')
    op.drop_index(op.f('ix_moodhistory_session_id'), table_name='moodhistory')
    op.drop_index(op.f('ix_moodhistory_id'), table_name='moodhistory')
    op.drop_index(op.f('ix_moodhistory_created_at'), table_name='moodhistory')
    op.drop_table('moodhistory')
    # ### end Alembic commands ###
