"""Create userfacts table

Revision ID: 9f8a6bc98432
Revises: 68c186d30cee
Create Date: 2025-12-07 14:43:08.147429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8a6bc98432'
down_revision = '68c186d30cee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign Key to users table'),
    sa.Column('fact_text', sa.Text(), nullable=False, comment="'User has a dog named Rex.'"),
    sa.Column('category', sa.String(length=50), nullable=False, comment="'Personal', 'Work', 'Family'. Helps filtering."),
    sa.Column('source', sa.String(length=50), nullable=False, comment="'conversation' or 'manual_input'."),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Context for the agent ('You told me this 2 years ago')."),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userfacts_category'), 'userfacts', ['category'], unique=False)
    op.create_index(op.f('ix_userfacts_created_at'), 'userfacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_userfacts_id'), 'userfacts', ['id'], unique=False)
    op.create_index(op.f('ix_userfacts_user_id'), 'userfacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userfacts_user_id'), table_name='userfacts')
    op.drop_index(op.f('ix_userfacts_id'), table_name='userfacts')
    op.drop_index(op.f('ix_userfacts_created_at'), table_name='userfacts')
    op.drop_index(op.f('ix_userfacts_category'), table_name='userfacts')
    op.drop_table('userfacts')
    # ### end Alembic commands ###
