"""Create users table

Revision ID: b699885a573a
Revises: 
Create Date: 2025-12-07 14:00:31.524381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b699885a573a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key - UUID'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Good for future auth/login'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="So the agent knows what to call the user (e.g., 'John')"),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Crucial. Store things like {'tone': 'friendly', 'verbose': false}. JSONB is faster than text metadata."),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="To calculate 'how long have we known each other'"),
    sa.Column('last_active', sa.DateTime(), nullable=False, comment="To welcome back a user ('I haven't seen you in a week!')"),
    sa.Column('hashed_password', sa.Text(), nullable=True, comment='Added to store the encrypted password (never store plain text!)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Added to allow you to ban users or handle email verification flows without deleting the record'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="Added in case you want an 'Admin' panel later to view all users"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
